<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="DummyInspection.cs" />
    <Compile Remove="Inspection.cs" />
    <Compile Remove="frmUnderInvestigation.cs" />
    <Compile Remove="frmUnderInvestigation.Designer.cs" />
    <Compile Remove="InvestigationData.cs" />
    <EmbeddedResource Remove="frmUnderInvestigation.resx" />
    <Compile Remove="Properties_Legacy\**" />
    <EmbeddedResource Remove="Properties_Legacy\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.8" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="9.0.2" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ApplicationData\ApplicationData.csproj" />
    <ProjectReference Include="..\CameraManager\CameraManager.csproj" />
    <ProjectReference Include="..\Constants\Constants.csproj" />
    <ProjectReference Include="..\DataManager\DataManager.csproj" />
    <ProjectReference Include="..\Delegates\Delegates.csproj" />
    <ProjectReference Include="..\Enums\Enums.csproj" />
    <ProjectReference Include="..\Interfacing\Interfacing.csproj" />
    <ProjectReference Include="..\IOClasses\IOClasses.csproj" />
    <ProjectReference Include="..\Messaging\Messaging.csproj" />
    <ProjectReference Include="..\mxClient\mxClient.csproj" />
    <ProjectReference Include="..\UtilityFunctions\UtilityFunctions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="AlkUSB3-64">
      <HintPath>..\References\AlkUSB3-64.dll</HintPath>
    </Reference>
    <Reference Include="Interop.OpenCVComMatcherLib">
      <HintPath>..\References\Interop.OpenCVComMatcherLib.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
