// ImageMatcher.h : Declaration of the CImageMatcher

#pragma once
#include "resource.h"       // main symbols
#include "OpenCVComMatcher_i.h" // Generated by MIDL based on the IDL file

#include <opencv2/opencv.hpp>
#include <vector>
#include <atlsafe.h> // Helper for SAFEARRAY
#include <tesseract/baseapi.h>
#include "../OCRAnalysis/include/OCRAnalysis.hpp"

#if defined(_WIN32_WCE) && !defined(_CE_DCOM) && !defined(_CE_ALLOW_SINGLE_THREADED_OBJECTS_IN_MTA)
#error "Single-threaded COM objects are not properly supported on Windows CE platform..."
#endif

using namespace ATL;

// CImageMatcher
struct ElementDef {
    long x = 0, y = 0, w = 0, h = 0;
    virtual ~ElementDef() = default;
};

struct TemplateDef : ElementDef {
    std::string filename;
};

struct TextDef : ElementDef {
    std::string searchText;
};

struct DataMatrixDef : ElementDef {
    std::string symbolData; // Expected data content
};

struct LabelDef {
    std::string name;
    std::vector<std::shared_ptr<ElementDef>> elements;
};
struct ImageDef {
    long clipX = 0, clipY = 0, clipWidth = 0, clipHeight = 0;
    long rotationAngle = 0;
};
class ATL_NO_VTABLE CImageMatcher :
    public CComObjectRootEx<CComMultiThreadModel>,
    public CComCoClass<CImageMatcher, &CLSID_ImageMatcher>,
    public IDispatchImpl<IImageMatcher, &IID_IImageMatcher, &LIBID_OpenCVComMatcherLib, /*wMajor =*/ 1, /*wMinor =*/ 0>
{
public:
    CImageMatcher() : m_pTessApi(nullptr), _imageNumber(1)
    {
        m_substitutionList.push_back(std::pair<std::string, std::string>("PRZ2", "PR2"));
        m_substitutionList.push_back(std::pair<std::string, std::string>("Bi ", "BI "));
        m_substitutionList.push_back(std::pair<std::string, std::string>("B1", "BI"));
    }

    DECLARE_REGISTRY_RESOURCEID(IDR_IMAGEMATCHER) // Make sure IDR_IMAGEMATCHER exists in resource.h

    BEGIN_COM_MAP(CImageMatcher)
        COM_INTERFACE_ENTRY(IImageMatcher)
        COM_INTERFACE_ENTRY(IDispatch)
    END_COM_MAP()

    DECLARE_PROTECT_FINAL_CONSTRUCT()

    HRESULT FinalConstruct()
    {
        return S_OK;
    }

    void FinalRelease();

public:
    // IImageMatcher Methods

    // Set the persistent source image with Rotation and Clipping
    STDMETHOD(SetSourceImage)(
        SAFEARRAY* imgData,
        LONG width,
        LONG height,
        LONG channels,
        BSTR xmlImageDef
        );

    // Match using stored source and byte-array template/mask
    STDMETHOD(MatchTemplate)(
        SAFEARRAY* templateImgData,
        LONG tmplWidth,
        LONG tmplHeight,
        LONG tmplChannels,
        SAFEARRAY* maskImgData,
        LONG maskWidth,
        LONG maskHeight,
        LONG maskChannels,
        LONG searchX,
        LONG searchY,
        LONG searchWidth,
        LONG searchHeight,
        LONG* matchX,
        LONG* matchY,
        DOUBLE* confidence,
        VARIANT_BOOL* found
        );

    // Match using stored source and file-path template/mask
    STDMETHOD(MatchTemplateFromFile)(
        BSTR templateFilePath,
        BSTR maskFilePath,
        LONG searchX,
        LONG searchY,
        LONG searchWidth,
        LONG searchHeight,
        LONG* matchX,
        LONG* matchY,
        DOUBLE* confidence,
        VARIANT_BOOL* found
        );

    // Find Data Matrices in the stored source image
    STDMETHOD(GetDataMatrices)(
        BSTR* jsonResult,
        VARIANT_BOOL* found
        );

    STDMETHOD(MatchTemplates)(
        SAFEARRAY* templateFilePaths,
        LONG searchX,
        LONG searchY,
        LONG searchWidth,
        LONG searchHeight,
        BSTR* jsonResult,
        VARIANT_BOOL* anyFound
        );

    STDMETHOD(PerformOCR)(
        BSTR language,
        LONG searchX,
        LONG searchY,
        LONG searchWidth,
        LONG searchHeight,
        BSTR* detectedText,
        DOUBLE* confidence,
        VARIANT_BOOL* success
        );

    STDMETHOD(SetLabelDefinition)(
        BSTR xmlLabelDef
        );

    STDMETHOD(PerformMatch)(
        SAFEARRAY* keys,
        SAFEARRAY* values,
        VARIANT_BOOL* result
        );
    STDMETHOD(GetMarkedImage)(
        SAFEARRAY** pImgData,
        LONG* width,
        LONG* height,
        LONG* channels
        );
    STDMETHOD(RetrieveNormalisedImage)(
        SAFEARRAY** pImgData,
        LONG* width,
        LONG* height,
        LONG* channels
        );

    STDMETHOD(CreateAbsoluteMap)(
        SAFEARRAY* imgData,
        LONG width, LONG height, LONG channels,
        BSTR l1PdfPath,
        BSTR l2PdfPath,
        DOUBLE dpi,
        VARIANT_BOOL markImage,
        BSTR imageFilePath,
        BSTR* jsonResult,
        VARIANT_BOOL* success
        );

    STDMETHOD(ComputeContentRect)(
        BSTR pdfPath,
        DOUBLE* minX,
        DOUBLE* minY,
        DOUBLE* maxX,
        DOUBLE* maxY,
        VARIANT_BOOL* success
        );

    std::string ApplySubstitutions(const std::string& input);
    cv::Mat ClipSourceToLargestObject(cv::Mat& src, int trough = 65);
    void Log(const char* fmt, ...);
    // Helper to remove whitespace from string
    std::string RemoveWhitespace(const std::string& input);
    // Substitution List
    std::vector<std::pair<std::string, std::string>> m_substitutionList;
    int GetHistogramTrough(const cv::UMat& graySrc);
    cv::Mat DrawHistogram(const cv::UMat& graySrc);

private:
    // Member variable to store the source image state
    // Now using UMat to keep image on OpenCL device/GPU
    cv::UMat m_CurrentSourceImageU;
    cv::Mat m_currentSourceImageM;
    cv::Mat m_MarkedSource;


    int _imageNumber;

    LabelDef m_currentLabelDef;
    tesseract::TessBaseAPI* m_pTessApi = nullptr;
    std::string m_currentTessLang;
    HRESULT MatToSafeArray(const cv::Mat& mat, SAFEARRAY** ppSA);

    // Helper to convert COM SAFEARRAY to OpenCV Mat
    HRESULT SafeArrayToMat(SAFEARRAY* pSA, int width, int height, int channels, cv::Mat& outMat);

    // Core logic shared by both COM methods (Private helper)
    // img parameter is UMat
    HRESULT MatchInternal(
        cv::UMat& img,
        cv::Mat& templ,
        cv::Mat& mask,
        cv::Rect searchRect,
        LONG* matchX,
        LONG* matchY,
        DOUBLE* confidence,
        VARIANT_BOOL* found
    );
    bool CheckText(const TextDef& def);
    bool CheckDataMatrix(const DataMatrixDef& def);
    // Internal helper to detect Data Matrices using ZXing
    // img parameter is UMat
    std::vector<cv::Rect> DetectDataMatrices(cv::UMat& img, std::vector<std::string>* outTexts = nullptr);

    // Internal Helper: Fill rectangle with color using mask
    // img parameter is UMat
    void FillRectMasked(cv::UMat& img, cv::Rect rect, cv::Scalar color, cv::Mat& mask);
    LabelDef ParseLabelXml(BSTR xmlStr);
    ImageDef ParseImageXml(BSTR xmlStr);
    tesseract::TessBaseAPI* GetTessApi(const char* lang);

public:
    // Extract images from a PDF file into a vector of cv::Mat
    HRESULT ExtractImagesFromPdf(const std::string& pdfFilePath, std::vector<cv::Mat>& images);
};

OBJECT_ENTRY_AUTO(__uuidof(ImageMatcher), CImageMatcher)