<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0-windows7.0</TargetFramework>
		<OutputType>Library</OutputType>
		<UseWindowsForms>true</UseWindowsForms>
		<ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
		<ImplicitUsings>enable</ImplicitUsings>
		<Platforms>AnyCPU;x64</Platforms>
	</PropertyGroup>
  <ItemGroup>
    <None Include="App.config" />
    <None Include="Properties\app.config">
      <SubType>Designer</SubType>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.8" />
    <PackageReference Include="MVTec.HalconDotNet-Windows" Version="22111.0.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="9.0.2" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="System.DirectoryServices.AccountManagement" Version="9.0.7" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\ApplicationData\ApplicationData\ApplicationData.csproj">
    </ProjectReference>
    <ProjectReference Include="..\..\Constants\Constants.csproj">
    </ProjectReference>
    <ProjectReference Include="..\..\DataManager\DataManager\DataManager.csproj">
    </ProjectReference>
    <ProjectReference Include="..\..\Enums\Enums.csproj">
    </ProjectReference>
  </ItemGroup>
</Project>