// ImageMatcher.h : Declaration of the CImageMatcher

#pragma once
#include "resource.h"       // main symbols
#include "ImageProcessorCom_i.h" // Generated by MIDL based on the IDL file

#include <opencv2/opencv.hpp>
#include <vector>
#include <atlsafe.h> // Helper for SAFEARRAY

#if defined(_WIN32_WCE) && !defined(_CE_DCOM) && !defined(_CE_ALLOW_SINGLE_THREADED_OBJECTS_IN_MTA)
#error "Single-threaded COM objects are not properly supported on Windows CE platform, such as the Windows Mobile platforms that do not include full DCOM support. Define _CE_ALLOW_SINGLE_THREADED_OBJECTS_IN_MTA to force ATL to support creating single-thread COM object's and allow use of it's single-threaded COM object implementations. The threading model in your rgs file was set to 'Free' as that is the only threading model supported in non DCOM Windows CE platforms."
#endif

using namespace ATL;

// CImageMatcher

class ATL_NO_VTABLE CImageMatcher :
    public CComObjectRootEx<CComMultiThreadModel>,
    public CComCoClass<CImageMatcher, &CLSID_ImageMatcher>,
    public IDispatchImpl<IImageMatcher, &IID_IImageMatcher, &LIBID_ImageProcessorCom, /*wMajor =*/ 1, /*wMinor =*/ 0>
{
public:
    CImageMatcher()
    {
    }

    DECLARE_REGISTRY_RESOURCEID(IDR_IMAGEMATCHER) // Make sure IDR_IMAGEMATCHER exists in resource.h

    BEGIN_COM_MAP(CImageMatcher)
        COM_INTERFACE_ENTRY(IImageMatcher)
        COM_INTERFACE_ENTRY(IDispatch)
    END_COM_MAP()

    DECLARE_PROTECT_FINAL_CONSTRUCT()

    HRESULT FinalConstruct()
    {
        return S_OK;
    }

    void FinalRelease()
    {
    }

public:
    // IImageMatcher Methods
    STDMETHOD(MatchTemplate)(
        SAFEARRAY* sourceImgData,
        LONG srcWidth,
        LONG srcHeight,
        LONG srcChannels,
        SAFEARRAY* templateImgData,
        LONG tmplWidth,
        LONG tmplHeight,
        LONG tmplChannels,
        LONG* matchX,
        LONG* matchY,
        DOUBLE* confidence,
        VARIANT_BOOL* found
        );

private:
    // Helper to convert COM SAFEARRAY to OpenCV Mat
    HRESULT SafeArrayToMat(SAFEARRAY* pSA, int width, int height, int channels, cv::Mat& outMat);
};

OBJECT_ENTRY_AUTO(__uuidof(ImageMatcher), CImageMatcher)